### ISSUE TITLE
Some random thoughts about documentation

### ISSUE THREAD

**Issue by svendahlstrand** [walle/cfg#1]
_The following message is written in Swedish._

**Korta första rubriken och texten därunder**
Det räcker med namnet: "underrubriken" (det efter strecket) kan dy flytta ner och göra till en ingress tillsammans med texten som redan finns där.

Texten som börjar med "The format is line [...]" och fram till "Example configuration" kan flytta in under rubriken "The format".

Texten som börjar med "The package also [...]" kan få rubriken "Marshalling" eller liknande.

Med åtgärderna ovan bör du få en kortare ingress som snabbare beskriver kärnan med projektet och dessutom kan du...

**Lyft exemplen i README längre upp och korta dem**
Lägg exemplen tidigt i README-filen, t.ex. innan rubriken "Marshalling". Eventuellt kan du även korta dem något (t.ex. göra konfigurationsfilen lite mindre "verbose").

Då får man tidigt ett hum om vad projektet hjälper en med.

**Ta bort myConfigEncoded från Marshall-exemplet?**
Det finns en konstant, `myConfigEcnoded`, i [Marshall-exemplet](https://godoc.org/github.com/walle/cfg#example-Marshal) som inte verkar fylla någon direkt funktion.

**Bestäm dig för marshall/unmarshall i stället för encode/decode**
Byt namn på filer för att bättre överensstämma med marshall/unmarshall.

**Comment by walle** [comment]
Bra kommentarer om att trycka ihop ingressen lite till. Har försökt göra det nu, tog med de flesta av dina förslag. Lyfte, men kortade inte exemplen. Ändrade dock användningsexemplet så det använder konfigurationen ovan, tror det blir lite mer beskrivande.

Perfekt, den hade jag missat. Exempeltester använder output istället för egna jämförelser.

Bytte inte namn på dessa. Anledningen till att de heter som de gör är att de gör det i JSON-paketet som ligger i standardbiblioteket. Där ligger de dock tillsammans med Encoder/Decoder typer, så vet inte om det är ett bra argument :) De får ligga kvar ett litet tag till, men ska komma ihåg att du föreslog att byta namn på dem.

Tack ska du ha för att du kikade igenom projektet!
